package com.example.tap_pay;

public enum RejectionReason {

    INVALID_SIGNATURE,
    DUPLICATE_NONCE,
    INVALID_DEVICE,
    USER_INACTIVE,
    RECEIVER_NOT_FOUND,
    INVALID_AMOUNT,
    OFFLINE_LIMIT_EXCEEDED,
    TRANSACTION_EXPIRED,
    INSUFFICIENT_BALANCE,
    INVALID_TIMESTAMP
}